# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20170425_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
