# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 13:32
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20170425_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_clip',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='post',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
